/* eslint-disable max-lines */
const drags = {
  BeBeZaharaBenet: {
    charisma: 55,
    uniqueness: 60,
    nerve: 85,
    talent: 75,
  },
  TyraSanchez: {
    charisma: 12,
    uniqueness: 35,
    nerve: 98,
    talent: 70,
  },
  RajaGemini: {
    charisma: 72,
    uniqueness: 85,
    nerve: 70,
    talent: 86,
  },
  SharonNeedles: {
    charisma: 41,
    uniqueness: 93,
    nerve: 69,
    talent: 70,
  },
  JinkxMonsoon: {
    charisma: 64,
    uniqueness: 82,
    nerve: 30,
    talent: 98,
  },
  BiancaDelRio: {
    charisma: 84,
    uniqueness: 97,
    nerve: 93,
    talent: 97,
  },
  VioletChachki: {
    charisma: 28,
    uniqueness: 88,
    nerve: 91,
    talent: 79,
  },
  BobtheDragQueen: {
    charisma: 99,
    uniqueness: 88,
    nerve: 89,
    talent: 99,
  },
  SashaVelour: {
    charisma: 68,
    uniqueness: 99,
    nerve: 79,
    talent: 100,
  },
  Aquaria: {
    charisma: 72,
    uniqueness: 65,
    nerve: 77,
    talent: 98,
  },
  YvieOddly: {
    charisma: 54,
    uniqueness: 100,
    nerve: 84,
    talent: 65,
  },
  JaidaEssenceHall: {
    charisma: 94,
    uniqueness: 67,
    nerve: 86,
    talent: 84,
  },
  Symone: {
    charisma: 88,
    uniqueness: 71,
    nerve: 76,
    talent: 89,
  },
  WillowPill: {
    charisma: 83,
    uniqueness: 98,
    nerve: 9,
    talent: 82,
  },
  ChadMichaels: {
    charisma: 45,
    uniqueness: 62,
    nerve: 80,
    talent: 84,
  },
  Alaska: {
    charisma: 94,
    uniqueness: 97,
    nerve: 68,
    talent: 92,
  },
  Shangela: {
    charisma: 87,
    uniqueness: 82,
    nerve: 99,
    talent: 86,
  },
  BendelaCreme: {
    charisma: 43,
    uniqueness: 88,
    nerve: 7,
    talent: 89,
  },
  AdoreDelano: {
    charisma: 91,
    uniqueness: 88,
    nerve: 23,
    talent: 80,
  },
  TrixieMatel: {
    charisma: 98,
    uniqueness: 91,
    nerve: 74,
    talent: 87,
  },
  SheaCoulee: {
    charisma: 92,
    uniqueness: 90,
    nerve: 91,
    talent: 97,
  },
  TrinityTheTuck: {
    charisma: 72,
    uniqueness: 69,
    nerve: 96,
    talent: 85,
  },
  MonetXChange: {
    charisma: 81,
    uniqueness: 52,
    nerve: 46,
    talent: 71,
  },
  Katya: {
    charisma: 99,
    uniqueness: 98,
    nerve: 79,
    talent: 90,
  },
  KylieSoniqueLove: {
    charisma: 79,
    uniqueness: 51,
    nerve: 49,
    talent: 74,
  },
  KimChi: {
    charisma: 18,
    uniqueness: 86,
    nerve: 14,
    talent: 71,
  },
  AlyssaEdwards: {
    charisma: 97,
    uniqueness: 100,
    nerve: 97,
    talent: 89,
  },
  PlastiqueTiara: {
    charisma: 61,
    uniqueness: 54,
    nerve: 19,
    talent: 79,
  },
  NaomiSmalls: {
    charisma: 60,
    uniqueness: 70,
    nerve: 100,
    talent: 62,
  },
  Valentina: {
    charisma: 88,
    uniqueness: 81,
    nerve: 89,
    talent: 83,
  },
  ManilaLuzon: {
    charisma: 92,
    uniqueness: 84,
    nerve: 76,
    talent: 89,
  },
  VanessaVanjieMateo: {
    charisma: 100,
    uniqueness: 94,
    nerve: 91,
    talent: 45,
  },
  CourtneyAct: {
    charisma: 73,
    uniqueness: 64,
    nerve: 86,
    talent: 86,
  },
  BrookeLynnHytes: {
    charisma: 81,
    uniqueness: 85,
    nerve: 84,
    talent: 91,
  },
  Detox: {
    charisma: 89,
    uniqueness: 96,
    nerve: 99,
    talent: 90,
  },
  MizCracker: {
    charisma: 80,
    uniqueness: 70,
    nerve: 69,
    talent: 88,
  },
  GigiGoode: {
    charisma: 26,
    uniqueness: 44,
    nerve: 49,
    talent: 81,
  },
  Willam: {
    charisma: 94,
    uniqueness: 88,
    nerve: 94,
    talent: 82,
  },
  Jujubee: {
    charisma: 99,
    uniqueness: 71,
    nerve: 93,
    talent: 87,
  },
  LatriceRoyale: {
    charisma: 99,
    uniqueness: 87,
    nerve: 96,
    talent: 90,
  },
  KameronMichaels: {
    charisma: 66,
    uniqueness: 58,
    nerve: 67,
    talent: 86,
  },
  Tatianna: {
    charisma: 79,
    uniqueness: 74,
    nerve: 98,
    talent: 90,
  },
};
export default drags;
